-- 식물 풀 - 초기화 시 등록되는 종 데이터
-- name: 한국 유통명(별칭), name_en: 학명, group_name: 그룹(물주기 동선 단위)
-- 물주기: 여름/겨울 권장 일수, 분갈이: 권장 개월 (일반적인 실내 재배 기준)
-- 유통명·학명·그룹은 풀이 기준(강제 갱신), 주기는 기존 값을 존중(비어있을 때만 채움)

INSERT INTO species (name, name_en, group_name, water_summer_days, water_winter_days, repot_months) VALUES
  -- 몬스테라
  ('몬스테라 델리시오사', 'Monstera deliciosa', '몬스테라', 7, 12, 12),
  ('몬스테라 아단소니', 'Monstera adansonii', '몬스테라', 7, 12, 12),
  ('민트 아단소니', 'Monstera adansonii ''Mint''', '몬스테라', 7, 12, 12),
  ('몬스테라 알보', 'Monstera deliciosa ''Albo Variegata''', '몬스테라', 7, 12, 12),
  ('몬스테라 타이 컨스텔레이션', 'Monstera deliciosa ''Thai Constellation''', '몬스테라', 7, 12, 12),
  ('몬스테라 두비아', 'Monstera dubia', '몬스테라', 7, 12, 12),
  ('몬스테라 스탠들리아나', 'Monstera standleyana', '몬스테라', 7, 12, 12),
  ('몬스테라 피나티파르티타', 'Monstera pinnatipartita', '몬스테라', 7, 12, 12),
  ('몬스테라 페루', 'Monstera karstenianum', '몬스테라', 8, 14, 12),
  -- 필로덴드론
  ('필로덴드론 버킨', 'Philodendron ''Birkin''', '필로덴드론', 7, 12, 12),
  ('필로덴드론 핑크프린세스', 'Philodendron erubescens ''Pink Princess''', '필로덴드론', 7, 12, 12),
  ('필로덴드론 미칸', 'Philodendron hederaceum var. hederaceum', '필로덴드론', 6, 10, 12),
  ('필로덴드론 옥시카르디움', 'Philodendron hederaceum', '필로덴드론', 6, 10, 12),
  ('필로덴드론 옥시카르디움 브라질', 'Philodendron hederaceum ''Brasil''', '필로덴드론', 6, 10, 12),
  ('필로덴드론 셀로움', 'Thaumatophyllum bipinnatifidum', '필로덴드론', 7, 12, 18),
  ('필로덴드론 콩고', 'Philodendron ''Congo''', '필로덴드론', 8, 14, 18),
  ('필로덴드론 글로리오섬', 'Philodendron gloriosum', '필로덴드론', 7, 12, 12),
  ('필로덴드론 멜라노크리섬', 'Philodendron melanochrysum', '필로덴드론', 7, 12, 12),
  ('필로덴드론 마요이', 'Philodendron mayoi', '필로덴드론', 7, 12, 12),
  ('필로덴드론 버럴막스', 'Philodendron burle-marxii', '필로덴드론', 6, 10, 12),
  ('필로덴드론 파라이소 베르디', 'Philodendron ''Paraiso Verde''', '필로덴드론', 7, 12, 12),
  ('필로덴드론 플로리다 뷰티', 'Philodendron ''Florida Beauty''', '필로덴드론', 7, 12, 12),
  ('필로덴드론 플로리다 뷰티 바리에가타', 'Philodendron ''Florida Beauty'' variegata', '필로덴드론', 7, 12, 12),
  ('필로덴드론 휘플웨이', 'Philodendron ''Whipple Way''', '필로덴드론', 7, 12, 12),
  ('필로덴드론 링 오브 파이어', 'Philodendron ''Ring of Fire''', '필로덴드론', 8, 14, 12),
  ('필로덴드론 베루코섬', 'Philodendron verrucosum', '필로덴드론', 7, 12, 12),
  ('필로덴드론 빌리에티에', 'Philodendron billietiae', '필로덴드론', 7, 12, 12),
  ('필로덴드론 파스타짜넘', 'Philodendron pastazanum', '필로덴드론', 7, 12, 12),
  ('필로덴드론 레몬라임', 'Philodendron hederaceum ''Lemon Lime''', '필로덴드론', 6, 10, 12),
  ('필로덴드론 화이트나이트', 'Philodendron erubescens ''White Knight''', '필로덴드론', 8, 14, 12),
  ('필로덴드론 화이트위저드', 'Philodendron erubescens ''White Wizard''', '필로덴드론', 8, 14, 12),
  ('필로덴드론 프린스 오브 오렌지', 'Philodendron ''Prince of Orange''', '필로덴드론', 7, 12, 12),
  ('필로덴드론 스쿠아미페룸', 'Philodendron squamiferum', '필로덴드론', 7, 12, 12),
  -- 스킨답서스 (에피프레넘 포함)
  ('스킨답서스', 'Epipremnum aureum', '스킨답서스', 7, 12, 12),
  ('스킨답서스 오레우스', 'Epipremnum aureum', '스킨답서스', 7, 12, 12),
  ('스킨답서스 마블퀸', 'Epipremnum aureum ''Marble Queen''', '스킨답서스', 7, 12, 12),
  ('스킨답서스 엔조이', 'Epipremnum aureum ''N''''Joy''', '스킨답서스', 7, 12, 12),
  ('스킨답서스 네온', 'Epipremnum aureum ''Neon''', '스킨답서스', 7, 12, 12),
  ('스킨답서스 글로벌그린', 'Epipremnum aureum ''Global Green''', '스킨답서스', 7, 12, 12),
  ('스킨답서스 트루비', 'Scindapsus treubii', '스킨답서스', 8, 14, 12),
  ('스킨답서스 트루비 문라이트', 'Scindapsus treubii ''Moonlight''', '스킨답서스', 8, 14, 12),
  ('스킨답서스 마야리', 'Scindapsus pictus ''Mayari''', '스킨답서스', 8, 14, 12),
  ('스킨답서스 실버 히어로', 'Scindapsus pictus ''Silver Hero''', '스킨답서스', 8, 14, 12),
  ('스킨답서스 픽투스', 'Scindapsus pictus', '스킨답서스', 8, 14, 12),
  ('스킨답서스 픽투스 엑조티카', 'Scindapsus pictus ''Exotica''', '스킨답서스', 8, 14, 12),
  ('스킨답서스 픽투스 아르지리우스', 'Scindapsus pictus ''Argyraeus''', '스킨답서스', 8, 14, 12),
  ('스킨답서스 실버리안', 'Scindapsus pictus ''Silvery Ann''', '스킨답서스', 8, 14, 12),
  ('에피프레넘 피나텀', 'Epipremnum pinnatum', '스킨답서스', 7, 12, 12),
  ('에피프레넘 피나텀 마블', 'Epipremnum pinnatum ''Marble''', '스킨답서스', 7, 12, 12),
  ('에피프레넘 피나텀 바리에가타', 'Epipremnum pinnatum ''Variegata''', '스킨답서스', 7, 12, 12),
  ('에피프레넘 세부블루', 'Epipremnum pinnatum ''Cebu Blue''', '스킨답서스', 7, 12, 12),
  -- 싱고니움
  ('싱고니움', 'Syngonium podophyllum', '싱고니움', 6, 10, 12),
  ('핑크 싱고니움', 'Syngonium podophyllum ''Neon Robusta''', '싱고니움', 6, 10, 12),
  ('싱고니움 알보', 'Syngonium podophyllum ''Albo Variegatum''', '싱고니움', 6, 10, 12),
  ('싱고니움 밀크컨페티', 'Syngonium podophyllum ''Milk Confetti''', '싱고니움', 6, 10, 12),
  ('싱고니움 레드스팟 트리컬러', 'Syngonium ''Red Spot Tricolor''', '싱고니움', 6, 10, 12),
  ('싱고니움 마리아', 'Syngonium podophyllum ''Maria''', '싱고니움', 6, 10, 12),
  ('싱고니움 바틱', 'Syngonium ''Batik''', '싱고니움', 6, 10, 12),
  -- 알로카시아
  ('알로카시아 프라이덱', 'Alocasia micholitziana ''Frydek''', '알로카시아', 6, 10, 12),
  ('알로카시아 아마조니카', 'Alocasia x amazonica', '알로카시아', 6, 10, 12),
  ('알로카시아 오도라', 'Alocasia odora', '알로카시아', 6, 10, 12),
  ('알로카시아 스팅레이', 'Alocasia macrorrhiza ''Stingray''', '알로카시아', 6, 10, 12),
  ('알로카시아 블랙벨벳', 'Alocasia reginula ''Black Velvet''', '알로카시아', 8, 14, 12),
  ('알로카시아 실버드래곤', 'Alocasia baginda ''Silver Dragon''', '알로카시아', 8, 14, 12),
  ('알로카시아 쿠쿨라타', 'Alocasia cucullata', '알로카시아', 6, 10, 12),
  ('알로카시아 마크로리조스', 'Alocasia macrorrhizos', '알로카시아', 6, 10, 12),
  -- 안스리움
  ('안스리움', 'Anthurium andraeanum', '안스리움', 7, 12, 12),
  ('안스리움 클라리네르비움', 'Anthurium clarinervium', '안스리움', 7, 12, 12),
  ('안스리움 비타리폴리움', 'Anthurium vittarifolium', '안스리움', 7, 12, 12),
  ('안스리움 크리스탈리눔', 'Anthurium crystallinum', '안스리움', 7, 12, 12),
  ('안스리움 와로퀘아눔', 'Anthurium warocqueanum', '안스리움', 7, 12, 12),
  ('안스리움 베이치', 'Anthurium veitchii', '안스리움', 7, 12, 12),
  -- 기타 관엽
  ('스파티필름', 'Spathiphyllum wallisii', '기타 관엽', 5, 9, 12),
  ('아글라오네마 스노우화이트', 'Aglaonema ''Snow White''', '기타 관엽', 8, 14, 12),
  ('아글라오네마 지리홍', 'Aglaonema ''Siam Aurora''', '기타 관엽', 8, 14, 12),
  ('아글라오네마 오로라', 'Aglaonema ''Aurora''', '기타 관엽', 8, 14, 12),
  ('디펜바키아', 'Dieffenbachia seguine', '기타 관엽', 7, 12, 12),
  ('디펜바키아 카밀라', 'Dieffenbachia ''Camille''', '기타 관엽', 7, 12, 12),
  ('칼라디움', 'Caladium bicolor', '기타 관엽', 5, 10, 12),
  ('금전수', 'Zamioculcas zamiifolia', '기타 관엽', 14, 28, 24),
  ('레이븐 금전수', 'Zamioculcas zamiifolia ''Raven''', '기타 관엽', 14, 28, 24),
  ('라피도포라 테트라스퍼마', 'Rhaphidophora tetrasperma', '기타 관엽', 7, 12, 12),
  ('라피도포라 하이', 'Rhaphidophora hayi', '기타 관엽', 7, 12, 12),
  ('쉐프렐라', 'Schefflera arboricola', '기타 관엽', 7, 12, 18),
  ('쉐프렐라 선버스터', 'Schefflera arboricola ''Sun Burst''', '기타 관엽', 7, 12, 18),
  ('홍콩야자', 'Schefflera arboricola', '기타 관엽', 7, 12, 18),
  ('팔손이', 'Fatsia japonica', '기타 관엽', 6, 11, 18),
  ('폴리셔스', 'Polyscias fruticosa', '기타 관엽', 7, 12, 18),
  ('크로톤', 'Codiaeum variegatum', '기타 관엽', 6, 11, 12),
  ('아펠란드라', 'Aphelandra squarrosa', '기타 관엽', 5, 9, 12),
  ('브레이니아 니보사', 'Breynia disticha', '기타 관엽', 5, 9, 12),
  ('마오리 소포라', 'Sophora prostrata ''Little Baby''', '기타 관엽', 5, 9, 12),
  ('트리안', 'Muehlenbeckia complexa', '기타 관엽', 4, 8, 12),
  ('뮬렌베키아', 'Muehlenbeckia complexa', '기타 관엽', 4, 8, 12),
  ('녹보수', 'Heteropanax fragrans', '기타 관엽', 8, 14, 18),
  ('해피트리', 'Radermachera sinica', '기타 관엽', 8, 14, 18),
  ('크루시아', 'Clusia rosea', '기타 관엽', 8, 14, 18),
  ('남천', 'Nandina domestica', '기타 관엽', 5, 10, 18),
  ('황칠나무', 'Dendropanax morbiferus', '기타 관엽', 6, 11, 18),
  ('아라우카리아', 'Araucaria heterophylla', '기타 관엽', 6, 11, 18),
  ('파키라', 'Pachira aquatica', '기타 관엽', 8, 14, 18),
  ('셀라기넬라', 'Selaginella tamariscina', '기타 관엽', 3, 6, 12),
  -- 칼라테아 (마란타류 포함)
  ('칼라테아 오르비폴리아', 'Goeppertia orbifolia', '칼라테아', 4, 8, 12),
  ('칼라테아 마코야나', 'Goeppertia makoyana', '칼라테아', 4, 8, 12),
  ('칼라테아 루피바르바', 'Goeppertia rufibarba', '칼라테아', 4, 8, 12),
  ('칼라테아 제브리나', 'Goeppertia zebrina', '칼라테아', 4, 8, 12),
  ('칼라테아 화이트퓨전', 'Goeppertia lietzei ''White Fusion''', '칼라테아', 4, 8, 12),
  ('칼라테아 로세오픽타', 'Goeppertia roseopicta', '칼라테아', 4, 8, 12),
  ('칼라테아 인시그니스', 'Goeppertia lancifolia', '칼라테아', 4, 8, 12),
  ('칼라테아 뮤사이카', 'Goeppertia kegeljanii ''Network''', '칼라테아', 4, 8, 12),
  ('마란타 레우코네우라', 'Maranta leuconeura', '칼라테아', 4, 8, 12),
  ('스트로만테 트리오스타', 'Stromanthe thalia ''Triostar''', '칼라테아', 4, 8, 12),
  ('크테난테 아마빌리스', 'Ctenanthe amabilis', '칼라테아', 4, 8, 12),
  -- 고무나무 (피쿠스)
  ('벤자민 고무나무', 'Ficus benjamina', '고무나무', 7, 12, 18),
  ('청짜보', 'Ficus benjamina ''Too Little''', '고무나무', 7, 12, 18),
  ('인도고무나무', 'Ficus elastica', '고무나무', 8, 14, 18),
  ('멜라니 고무나무', 'Ficus elastica ''Melany''', '고무나무', 8, 14, 18),
  ('루비 고무나무', 'Ficus elastica ''Ruby''', '고무나무', 8, 14, 18),
  ('수채화 고무나무', 'Ficus elastica ''Tineke''', '고무나무', 8, 14, 18),
  ('버건디 고무나무', 'Ficus elastica ''Burgundy''', '고무나무', 8, 14, 18),
  ('떡갈고무나무', 'Ficus lyrata', '고무나무', 7, 12, 18),
  ('벵갈고무나무', 'Ficus benghalensis', '고무나무', 7, 12, 18),
  ('움베르타', 'Ficus umbellata', '고무나무', 7, 12, 18),
  ('대만고무나무', 'Ficus microcarpa', '고무나무', 7, 12, 18),
  ('푸미라', 'Ficus pumila', '고무나무', 4, 8, 12),
  ('제주애기모람', 'Ficus thunbergii', '고무나무', 4, 8, 12),
  ('알리 고무나무', 'Ficus binnendijkii ''Alii''', '고무나무', 7, 12, 18),
  -- 야자 (대형 잎보기 포함)
  ('테이블야자', 'Chamaedorea elegans', '야자', 7, 12, 18),
  ('아레카야자', 'Dypsis lutescens', '야자', 6, 11, 18),
  ('켄챠야자', 'Howea forsteriana', '야자', 8, 14, 24),
  ('관음죽', 'Rhapis excelsa', '야자', 8, 14, 24),
  ('종려죽', 'Rhapis humilis', '야자', 8, 14, 24),
  ('캣야자', 'Chamaedorea cataractarum', '야자', 7, 12, 18),
  ('피닉스야자', 'Phoenix roebelenii', '야자', 7, 12, 24),
  ('소철', 'Cycas revoluta', '야자', 10, 21, 24),
  ('극락조', 'Strelitzia nicolai', '야자', 7, 12, 18),
  ('여인초', 'Ravenala madagascariensis', '야자', 7, 12, 18),
  ('파초', 'Musa basjoo', '야자', 5, 10, 12),
  -- 드라세나 (유카 포함)
  ('행운목', 'Dracaena fragrans ''Massangeana''', '드라세나', 10, 18, 18),
  ('드라세나 마지나타', 'Dracaena marginata', '드라세나', 10, 18, 18),
  ('드라세나 콤팩타', 'Dracaena deremensis ''Compacta''', '드라세나', 10, 18, 18),
  ('드라세나 와네키', 'Dracaena deremensis ''Warneckii''', '드라세나', 10, 18, 18),
  ('드라세나 수르쿨로사', 'Dracaena surculosa', '드라세나', 9, 16, 18),
  ('드라세나 수르쿨로사 밀키웨이', 'Dracaena surculosa ''Milky Way''', '드라세나', 9, 16, 18),
  ('드라세나 송오브인디아', 'Dracaena reflexa ''Song of India''', '드라세나', 10, 18, 18),
  ('드라세나 송오브자메이카', 'Dracaena reflexa ''Song of Jamaica''', '드라세나', 10, 18, 18),
  ('유카', 'Yucca elephantipes', '드라세나', 12, 24, 24),
  -- 산세베리아
  ('산세베리아', 'Dracaena trifasciata', '산세베리아', 14, 28, 24),
  ('산세베리아 문샤인', 'Dracaena trifasciata ''Moonshine''', '산세베리아', 14, 28, 24),
  ('스투키', 'Dracaena angolensis', '산세베리아', 14, 30, 24),
  ('산세베리아 스투키', 'Dracaena stuckyi', '산세베리아', 14, 30, 24),
  ('산세베리아 하니', 'Dracaena trifasciata ''Hahnii''', '산세베리아', 14, 28, 24),
  ('산세베리아 킬리만자로', 'Dracaena kirkii', '산세베리아', 14, 28, 24),
  -- 아이비 (헤데라)
  ('아이비', 'Hedera helix', '아이비', 5, 9, 12),
  ('하트아이비', 'Hedera hibernica', '아이비', 5, 9, 12),
  ('반딧불이아이비', 'Hedera helix ''Firefly''', '아이비', 5, 9, 12),
  ('골든잉곳아이비', 'Hedera helix ''Golden Ingot''', '아이비', 5, 9, 12),
  ('달마시안 아이비', 'Hedera helix ''Dalmatian''', '아이비', 5, 9, 12),
  ('윌리 아이비', 'Hedera helix ''Willy''', '아이비', 5, 9, 12),
  ('잉글리시 아이비', 'Hedera helix', '아이비', 5, 9, 12),
  -- 호야
  ('호야 카르노사', 'Hoya carnosa', '호야', 10, 18, 24),
  ('호야 콤팩타', 'Hoya carnosa ''Compacta''', '호야', 10, 18, 24),
  ('호야 케리', 'Hoya kerrii', '호야', 12, 21, 24),
  ('호야 라쿠노사', 'Hoya lacunosa', '호야', 9, 16, 24),
  ('호야 빌로바타', 'Hoya bilobata', '호야', 9, 16, 24),
  ('호야 크라시페티올라타', 'Hoya crassipetiolata', '호야', 10, 18, 24),
  ('호야 로툰디플로라', 'Hoya rotundiflora', '호야', 9, 16, 24),
  ('호야 크로니아나', 'Hoya krohniana', '호야', 9, 16, 24),
  ('호야 크로니아나 슈퍼에스키모', 'Hoya krohniana ''Super Eskimo''', '호야', 9, 16, 24),
  ('호야 휴스켈리아나', 'Hoya heuschkeliana', '호야', 9, 16, 24),
  ('호야 휴스켈리아나 바리에가타', 'Hoya heuschkeliana ''Variegata''', '호야', 9, 16, 24),
  ('호야 윌버그레이브', 'Hoya ''Wilbur Graves''', '호야', 10, 18, 24),
  ('호야 마틸데', 'Hoya ''Mathilde''', '호야', 10, 18, 24),
  ('호야 리네아리스', 'Hoya linearis', '호야', 8, 14, 24),
  ('호야 오보바타', 'Hoya obovata', '호야', 12, 21, 24),
  ('호야 푸베라', 'Hoya pubera', '호야', 9, 16, 24),
  ('호야 벨라', 'Hoya bella', '호야', 9, 16, 24),
  ('호야 레츠사', 'Hoya retusa', '호야', 8, 14, 24),
  ('호야 시기라리스', 'Hoya sigillatis', '호야', 10, 18, 24),
  ('호야 폴리네우라', 'Hoya polyneura', '호야', 9, 16, 24),
  -- 페페로미아 (필레아·소형 포함)
  ('페페로미아 옵투시폴리아', 'Peperomia obtusifolia', '페페로미아', 9, 16, 12),
  ('수박 페페로미아', 'Peperomia argyreia', '페페로미아', 8, 14, 12),
  ('페페로미아 안굴라타', 'Peperomia angulata', '페페로미아', 8, 14, 12),
  ('페페로미아 카페라타', 'Peperomia caperata', '페페로미아', 8, 14, 12),
  ('페페로미아 호프', 'Peperomia ''Hope''', '페페로미아', 9, 16, 12),
  ('페페로미아 프로스트', 'Peperomia caperata ''Frost''', '페페로미아', 8, 14, 12),
  ('필레아 페페로미오이데스', 'Pilea peperomioides', '페페로미아', 8, 14, 12),
  ('필레아 글라우카', 'Pilea glauca', '페페로미아', 6, 11, 12),
  ('필레아 카디에레이', 'Pilea cadierei', '페페로미아', 6, 11, 12),
  ('베고니아 마쿨라타', 'Begonia maculata', '페페로미아', 6, 11, 12),
  ('베고니아 렉스', 'Begonia rex', '페페로미아', 5, 10, 12),
  ('베고니아 마소니아나', 'Begonia masoniana', '페페로미아', 5, 10, 12),
  ('피토니아', 'Fittonia albivenis', '페페로미아', 3, 6, 12),
  ('트라데스칸티아 제브리나', 'Tradescantia zebrina', '페페로미아', 5, 9, 12),
  ('아프리칸 바이올렛', 'Saintpaulia ionantha', '페페로미아', 6, 10, 12),
  -- 행잉·공중식물
  ('틸란드시아', 'Tillandsia', '행잉', 7, 10, NULL),
  ('틸란드시아 이오난사', 'Tillandsia ionantha', '행잉', 7, 10, NULL),
  ('틸란드시아 세로그라피카', 'Tillandsia xerographica', '행잉', 10, 14, NULL),
  ('수염 틸란드시아', 'Tillandsia usneoides', '행잉', 5, 8, NULL),
  ('립살리스 카스타', 'Rhipsalis cassutha', '행잉', 9, 16, 18),
  ('립살리스 파라독사', 'Rhipsalis paradoxa', '행잉', 9, 16, 18),
  ('디시디아', 'Dischidia', '행잉', 9, 16, 18),
  ('디시디아 넘물라리아', 'Dischidia nummularia', '행잉', 9, 16, 18),
  ('러브체인', 'Ceropegia woodii', '행잉', 10, 18, 18),
  ('녹영', 'Curio rowleyanus', '행잉', 12, 21, 18),
  -- 고사리
  ('보스턴고사리', 'Nephrolepis exaltata', '고사리', 3, 6, 12),
  ('아디안텀', 'Adiantum raddianum', '고사리', 3, 5, 12),
  ('박쥐란', 'Platycerium bifurcatum', '고사리', 6, 10, 18),
  ('블루스타펀', 'Phlebodium aureum', '고사리', 4, 8, 12),
  ('아비스', 'Asplenium nidus ''Avis''', '고사리', 4, 8, 12),
  ('넉줄고사리', 'Davallia mariesii', '고사리', 4, 8, 12),
  ('프테리스', 'Pteris cretica', '고사리', 3, 6, 12),
  -- 허브
  ('로즈마리', 'Salvia rosmarinus', '허브', 3, 7, 12),
  ('라벤더', 'Lavandula angustifolia', '허브', 4, 8, 12),
  ('바질', 'Ocimum basilicum', '허브', 2, 5, 6),
  ('애플민트', 'Mentha suaveolens', '허브', 2, 5, 6),
  ('페퍼민트', 'Mentha x piperita', '허브', 2, 5, 6),
  ('스피아민트', 'Mentha spicata', '허브', 2, 5, 6),
  ('레몬밤', 'Melissa officinalis', '허브', 3, 6, 6),
  ('세이지', 'Salvia officinalis', '허브', 4, 8, 12),
  ('오레가노', 'Origanum vulgare', '허브', 4, 8, 12),
  ('장미허브', 'Plectranthus tomentosa', '허브', 4, 8, 12),
  ('타임', 'Thymus vulgaris', '허브', 4, 8, 12),
  ('유칼립투스 폴리안', 'Eucalyptus polyanthemos', '허브', 3, 7, 12),
  ('유칼립투스 구니', 'Eucalyptus gunnii', '허브', 3, 7, 12),
  ('율마', 'Cupressus macrocarpa ''Goldcrest''', '허브', 3, 6, 12),
  -- 꽃·나무
  ('재스민', 'Jasminum polyanthum', '꽃·나무', 4, 8, 12),
  ('마다가스카르 자스민', 'Stephanotis floribunda', '꽃·나무', 5, 9, 12),
  ('치자나무', 'Gardenia jasminoides', '꽃·나무', 4, 8, 12),
  ('아라비카 커피나무', 'Coffea arabica', '꽃·나무', 4, 8, 12),
  ('올리브나무', 'Olea europaea', '꽃·나무', 5, 10, 18),
  ('레몬나무', 'Citrus limon', '꽃·나무', 5, 10, 18),
  ('무화과나무', 'Ficus carica', '꽃·나무', 4, 9, 18),
  ('석류나무', 'Punica granatum', '꽃·나무', 5, 10, 18),
  ('블루베리', 'Vaccinium corymbosum', '꽃·나무', 3, 7, 12),
  ('금목서', 'Osmanthus fragrans', '꽃·나무', 5, 10, 18),
  ('동백나무', 'Camellia japonica', '꽃·나무', 5, 9, 18),
  ('수국', 'Hydrangea macrophylla', '꽃·나무', 3, 7, 12),
  ('제라늄', 'Pelargonium inquinans', '꽃·나무', 5, 10, 12),
  ('구문초', 'Pelargonium graveolens', '꽃·나무', 4, 8, 12),
  ('시클라멘', 'Cyclamen persicum', '꽃·나무', 4, 7, 12),
  ('포인세티아', 'Euphorbia pulcherrima', '꽃·나무', 5, 9, 12),
  ('꽃기린', 'Euphorbia milii', '꽃·나무', 10, 18, 24),
  -- 난초
  ('호접란', 'Phalaenopsis', '난초', 10, 14, 24),
  ('만천홍', 'Phalaenopsis ''Mancheonhong''', '난초', 10, 14, 24),
  ('덴드로비움', 'Dendrobium', '난초', 8, 14, 24),
  ('풍란', 'Neofinetia falcata', '난초', 7, 12, 24),
  -- 다육·선인장 (괴근 포함)
  ('선인장', 'Cactaceae', '다육·선인장', 14, 35, 24),
  ('금호선인장', 'Echinocactus grusonii', '다육·선인장', 15, 40, 24),
  ('백도선', 'Opuntia microdasys var. albispina', '다육·선인장', 14, 35, 24),
  ('귀면각', 'Cereus peruvianus', '다육·선인장', 14, 35, 24),
  ('용신목', 'Myrtillocactus geometrizans', '다육·선인장', 14, 35, 24),
  ('게발선인장', 'Schlumbergera truncata', '다육·선인장', 10, 18, 24),
  ('에케베리아', 'Echeveria', '다육·선인장', 14, 30, 24),
  ('하월시아', 'Haworthia', '다육·선인장', 14, 28, 24),
  ('십이지권', 'Haworthiopsis fasciata', '다육·선인장', 14, 28, 24),
  ('염좌', 'Crassula ovata', '다육·선인장', 14, 28, 24),
  ('흑법사', 'Aeonium arboreum ''Zwartkop''', '다육·선인장', 12, 25, 24),
  ('을녀심', 'Sedum pachyphyllum', '다육·선인장', 12, 25, 24),
  ('벽어연', 'Corpuscularia lehmannii', '다육·선인장', 14, 28, 24),
  ('리톱스', 'Lithops', '다육·선인장', 20, 60, 24),
  ('세덤', 'Sedum', '다육·선인장', 12, 25, 24),
  ('세덤 버리토', 'Sedum morganianum ''Burrito''', '다육·선인장', 12, 25, 24),
  ('알로에 베라', 'Aloe vera', '다육·선인장', 14, 30, 24),
  ('칼랑코에', 'Kalanchoe blossfeldiana', '다육·선인장', 10, 18, 24),
  ('아가베', 'Agave', '다육·선인장', 15, 35, 24),
  ('유포르비아 트리고나', 'Euphorbia trigona', '다육·선인장', 14, 30, 24),
  ('아데니움 오베숨', 'Adenium obesum', '다육·선인장', 10, 30, 24),
  ('스테파니아 에렉타', 'Stephania erecta', '다육·선인장', 10, 30, 24),
  ('시조바시스 인트리카타', 'Schizobasis intricata', '다육·선인장', 12, 30, 24),
  ('파키포디움', 'Pachypodium', '다육·선인장', 10, 30, 24)
ON CONFLICT(name) DO UPDATE SET
  name_en           = excluded.name_en,
  group_name        = excluded.group_name,
  water_summer_days = COALESCE(species.water_summer_days, excluded.water_summer_days),
  water_winter_days = COALESCE(species.water_winter_days, excluded.water_winter_days),
  repot_months      = COALESCE(species.repot_months, excluded.repot_months);

-- 유통명 정정으로 대체된 옛 항목 제거 (식물이 참조 중이면 유지)
DELETE FROM species WHERE name IN
  ('스킨답서스 실버레이디', '제트 플루미사', '필로덴드론 웜비', '싱고니움 배티크',
   '테이블용 겐차야자', '당나귀꼬리', '안스리움 안드레아눔')
  AND id NOT IN (SELECT DISTINCT species_id FROM plants WHERE species_id IS NOT NULL);
