-- 식물 풀 - 초기화 시 등록되는 종 데이터
-- name: 표기용(한글 우선), name_en: 영문·학명(검색용)
-- 물주기: 여름/겨울 권장 일수, 분갈이: 권장 개월 (일반적인 실내 재배 기준)
-- 이미 존재하는 종은 비어있는 값만 채운다 (사용자 데이터 존중).

INSERT INTO species (name, name_en, water_summer_days, water_winter_days, repot_months) VALUES
  -- 몬스테라
  ('몬스테라 델리시오사', 'Monstera deliciosa', 7, 12, 12),
  ('몬스테라 아단소니', 'Monstera adansonii', 7, 12, 12),
  ('민트 아단소니', 'Monstera adansonii Mint', 7, 12, 12),
  ('몬스테라 알보', 'Monstera deliciosa Albo Variegata', 7, 12, 12),
  ('몬스테라 타이 컨스텔레이션', 'Monstera Thai Constellation', 7, 12, 12),
  ('몬스테라 두비아', 'Monstera dubia', 7, 12, 12),
  ('몬스테라 스탠들리아나', 'Monstera standleyana', 7, 12, 12),
  ('몬스테라 피나티파르티타', 'Monstera pinnatipartita', 7, 12, 12),
  ('몬스테라 페루', 'Monstera karstenianum Peru', 8, 14, 12),
  -- 필로덴드론
  ('필로덴드론 버킨', 'Philodendron Birkin', 7, 12, 12),
  ('필로덴드론 핑크프린세스', 'Philodendron Pink Princess', 7, 12, 12),
  ('필로덴드론 미칸', 'Philodendron Micans', 6, 10, 12),
  ('필로덴드론 옥시카르디움', 'Philodendron hederaceum Oxycardium', 6, 10, 12),
  ('필로덴드론 옥시카르디움 브라질', 'Philodendron hederaceum Brasil', 6, 10, 12),
  ('필로덴드론 셀로움', 'Philodendron Selloum', 7, 12, 18),
  ('필로덴드론 콩고', 'Philodendron Congo', 8, 14, 18),
  ('필로덴드론 글로리오섬', 'Philodendron gloriosum', 7, 12, 12),
  ('필로덴드론 멜라노크리섬', 'Philodendron melanochrysum', 7, 12, 12),
  ('필로덴드론 마요이', 'Philodendron mayoi', 7, 12, 12),
  ('필로덴드론 버럴막스', 'Philodendron Burle Marx', 6, 10, 12),
  ('필로덴드론 파라이소 베르디', 'Philodendron Paraiso Verde', 7, 12, 12),
  ('필로덴드론 플로리다 뷰티', 'Philodendron Florida Beauty', 7, 12, 12),
  ('필로덴드론 플로리다 뷰티 바리에가타', 'Philodendron Florida Beauty Variegata', 7, 12, 12),
  ('필로덴드론 웜비', 'Philodendron Whipple Way', 7, 12, 12),
  ('필로덴드론 링 오브 파이어', 'Philodendron Ring of Fire', 8, 14, 12),
  ('필로덴드론 베루코섬', 'Philodendron verrucosum', 7, 12, 12),
  ('필로덴드론 빌리에티에', 'Philodendron billietiae', 7, 12, 12),
  ('필로덴드론 파스타짜넘', 'Philodendron pastazanum', 7, 12, 12),
  ('필로덴드론 레몬라임', 'Philodendron Lemon Lime', 6, 10, 12),
  ('필로덴드론 화이트나이트', 'Philodendron White Knight', 8, 14, 12),
  ('필로덴드론 화이트위저드', 'Philodendron White Wizard', 8, 14, 12),
  ('필로덴드론 프린스 오브 오렌지', 'Philodendron Prince of Orange', 7, 12, 12),
  ('필로덴드론 스쿠아미페룸', 'Philodendron squamiferum', 7, 12, 12),
  -- 스킨답서스·에피프레넘
  ('스킨답서스', 'Pothos (Epipremnum aureum)', 7, 12, 12),
  ('스킨답서스 오레우스', 'Golden Pothos', 7, 12, 12),
  ('스킨답서스 마블퀸', 'Pothos Marble Queen', 7, 12, 12),
  ('스킨답서스 엔조이', 'Pothos N''Joy', 7, 12, 12),
  ('스킨답서스 네온', 'Pothos Neon', 7, 12, 12),
  ('스킨답서스 글로벌그린', 'Pothos Global Green', 7, 12, 12),
  ('스킨답서스 트루비', 'Scindapsus treubii', 8, 14, 12),
  ('스킨답서스 트루비 문라이트', 'Scindapsus treubii Moonlight', 8, 14, 12),
  ('스킨답서스 마야리', 'Scindapsus pictus Mayari', 8, 14, 12),
  ('스킨답서스 실버 히어로', 'Scindapsus pictus Silver Hero', 8, 14, 12),
  ('스킨답서스 픽투스', 'Satin Pothos (Scindapsus pictus)', 8, 14, 12),
  ('스킨답서스 픽투스 엑조티카', 'Scindapsus pictus Exotica', 8, 14, 12),
  ('스킨답서스 픽투스 아르지리우스', 'Scindapsus pictus Argyraeus', 8, 14, 12),
  ('스킨답서스 실버레이디', 'Scindapsus pictus Silvery Ann', 8, 14, 12),
  ('에피프레넘 피나텀', 'Epipremnum pinnatum', 7, 12, 12),
  ('에피프레넘 피나텀 마블', 'Epipremnum pinnatum Marble', 7, 12, 12),
  ('에피프레넘 피나텀 바리에가타', 'Epipremnum pinnatum Variegata', 7, 12, 12),
  ('에피프레넘 세부블루', 'Epipremnum pinnatum Cebu Blue', 7, 12, 12),
  -- 싱고니움
  ('싱고니움', 'Arrowhead Plant (Syngonium)', 6, 10, 12),
  ('핑크 싱고니움', 'Syngonium Pink', 6, 10, 12),
  ('싱고니움 알보', 'Syngonium Albo Variegata', 6, 10, 12),
  ('싱고니움 밀크컨페티', 'Syngonium Milk Confetti', 6, 10, 12),
  ('싱고니움 레드스팟 트리컬러', 'Syngonium Red Spot Tricolor', 6, 10, 12),
  ('싱고니움 마리아', 'Syngonium Maria', 6, 10, 12),
  ('싱고니움 배티크', 'Syngonium Batik', 6, 10, 12),
  -- 알로카시아·안스리움·기타 천남성과
  ('알로카시아 프라이덱', 'Alocasia Frydek', 6, 10, 12),
  ('알로카시아 아마조니카', 'Alocasia Amazonica', 6, 10, 12),
  ('알로카시아 오도라', 'Alocasia odora', 6, 10, 12),
  ('알로카시아 스팅레이', 'Alocasia Stingray', 6, 10, 12),
  ('알로카시아 블랙벨벳', 'Alocasia Black Velvet', 8, 14, 12),
  ('알로카시아 실버드래곤', 'Alocasia Silver Dragon', 8, 14, 12),
  ('알로카시아 쿠쿨라타', 'Alocasia cucullata', 6, 10, 12),
  ('알로카시아 마크로리조스', 'Alocasia macrorrhizos', 6, 10, 12),
  ('안스리움 안드레아눔', 'Anthurium andraeanum', 7, 12, 12),
  ('안스리움 클라리네르비움', 'Anthurium clarinervium', 7, 12, 12),
  ('안스리움 비타리폴리움', 'Anthurium vittarifolium', 7, 12, 12),
  ('안스리움 크리스탈리눔', 'Anthurium crystallinum', 7, 12, 12),
  ('안스리움 와로퀘아눔', 'Anthurium warocqueanum', 7, 12, 12),
  ('안스리움 베이치', 'Anthurium veitchii', 7, 12, 12),
  ('스파티필름', 'Peace Lily (Spathiphyllum)', 5, 9, 12),
  ('아글라오네마 스노우화이트', 'Aglaonema Snow White', 8, 14, 12),
  ('아글라오네마 지리홍', 'Aglaonema Red', 8, 14, 12),
  ('아글라오네마 오로라', 'Aglaonema Aurora', 8, 14, 12),
  ('디펜바키아', 'Dieffenbachia', 7, 12, 12),
  ('디펜바키아 카밀라', 'Dieffenbachia Camille', 7, 12, 12),
  ('칼라디움', 'Caladium', 5, 10, 12),
  ('금전수', 'ZZ Plant (Zamioculcas zamiifolia)', 14, 28, 24),
  ('라피도포라 테트라스퍼마', 'Rhaphidophora tetrasperma', 7, 12, 12),
  ('라피도포라 하이', 'Rhaphidophora hayi', 7, 12, 12),
  ('제트 플루미사', 'Zamioculcas zamiifolia Raven', 14, 28, 24),
  -- 칼라테아·마란타
  ('칼라테아 오르비폴리아', 'Calathea orbifolia', 4, 8, 12),
  ('칼라테아 마코야나', 'Calathea makoyana', 4, 8, 12),
  ('칼라테아 루피바르바', 'Calathea rufibarba', 4, 8, 12),
  ('칼라테아 제브리나', 'Calathea zebrina', 4, 8, 12),
  ('칼라테아 화이트퓨전', 'Calathea White Fusion', 4, 8, 12),
  ('칼라테아 로세오픽타', 'Calathea roseopicta', 4, 8, 12),
  ('칼라테아 인시그니스', 'Calathea lancifolia (Rattlesnake)', 4, 8, 12),
  ('칼라테아 뮤사이카', 'Calathea musaica Network', 4, 8, 12),
  ('마란타 레우코네우라', 'Prayer Plant (Maranta leuconeura)', 4, 8, 12),
  ('스트로만테 트리오스타', 'Stromanthe Triostar', 4, 8, 12),
  ('크테난테 아마빌리스', 'Ctenanthe amabilis', 4, 8, 12),
  -- 고무나무(피쿠스)
  ('벤자민 고무나무', 'Weeping Fig (Ficus benjamina)', 7, 12, 18),
  ('청짜보', 'Ficus benjamina Too Little', 7, 12, 18),
  ('인도고무나무', 'Rubber Plant (Ficus elastica)', 8, 14, 18),
  ('멜라니 고무나무', 'Ficus elastica Melany', 8, 14, 18),
  ('루비 고무나무', 'Ficus elastica Ruby', 8, 14, 18),
  ('수채화 고무나무', 'Ficus elastica Tineke', 8, 14, 18),
  ('버건디 고무나무', 'Ficus elastica Burgundy', 8, 14, 18),
  ('떡갈고무나무', 'Fiddle Leaf Fig (Ficus lyrata)', 7, 12, 18),
  ('벵갈고무나무', 'Ficus benghalensis', 7, 12, 18),
  ('움베르타', 'Ficus umbellata', 7, 12, 18),
  ('대만고무나무', 'Ficus microcarpa (Ginseng)', 7, 12, 18),
  ('푸미라', 'Creeping Fig (Ficus pumila)', 4, 8, 12),
  ('제주애기모람', 'Ficus thunbergii', 4, 8, 12),
  ('알리 고무나무', 'Ficus binnendijkii Alii', 7, 12, 18),
  -- 야자·소철
  ('테이블야자', 'Parlor Palm (Chamaedorea elegans)', 7, 12, 18),
  ('아레카야자', 'Areca Palm (Dypsis lutescens)', 6, 11, 18),
  ('켄챠야자', 'Kentia Palm (Howea forsteriana)', 8, 14, 24),
  ('관음죽', 'Lady Palm (Rhapis excelsa)', 8, 14, 24),
  ('종려죽', 'Slender Lady Palm (Rhapis humilis)', 8, 14, 24),
  ('테이블용 겐차야자', 'Chamaedorea cataractarum', 7, 12, 18),
  ('피닉스야자', 'Pygmy Date Palm (Phoenix roebelenii)', 7, 12, 24),
  ('소철', 'Sago Palm (Cycas revoluta)', 10, 21, 24),
  ('극락조', 'Bird of Paradise (Strelitzia nicolai)', 7, 12, 18),
  ('여인초', 'Traveller''s Palm (Ravenala)', 7, 12, 18),
  ('파초', 'Japanese Banana (Musa basjoo)', 5, 10, 12),
  -- 드라세나·유카
  ('행운목', 'Corn Plant (Dracaena fragrans Massangeana)', 10, 18, 18),
  ('드라세나 마지나타', 'Dragon Tree (Dracaena marginata)', 10, 18, 18),
  ('드라세나 콤팩타', 'Dracaena Compacta', 10, 18, 18),
  ('드라세나 와네키', 'Dracaena Warneckii', 10, 18, 18),
  ('드라세나 수르쿨로사', 'Gold Dust Dracaena (Dracaena surculosa)', 9, 16, 18),
  ('드라세나 수르쿨로사 밀키웨이', 'Dracaena surculosa Milky Way', 9, 16, 18),
  ('드라세나 송오브인디아', 'Dracaena Song of India', 10, 18, 18),
  ('드라세나 송오브자메이카', 'Dracaena Song of Jamaica', 10, 18, 18),
  ('유카', 'Yucca', 12, 24, 24),
  ('녹보수', 'Heteropanax fragrans', 8, 14, 18),
  ('해피트리', 'Happy Tree (Radermachera)', 8, 14, 18),
  -- 산세베리아
  ('산세베리아', 'Snake Plant (Sansevieria trifasciata)', 14, 28, 24),
  ('산세베리아 문샤인', 'Sansevieria Moonshine', 14, 28, 24),
  ('산세베리아 스투키', 'Sansevieria stuckyi', 14, 30, 24),
  ('산세베리아 하니', 'Sansevieria Hahnii', 14, 28, 24),
  ('산세베리아 킬리만자로', 'Sansevieria kirkii', 14, 28, 24),
  -- 쉐프렐라·아이비·헤데라
  ('쉐프렐라', 'Umbrella Tree (Schefflera arboricola)', 7, 12, 18),
  ('쉐프렐라 선버스터', 'Schefflera Sunburst', 7, 12, 18),
  ('홍콩야자', 'Dwarf Umbrella Tree', 7, 12, 18),
  ('팔손이', 'Japanese Aralia (Fatsia japonica)', 6, 11, 18),
  ('아이비', 'English Ivy (Hedera helix)', 5, 9, 12),
  ('하트아이비', 'Sweetheart Ivy (Hedera hibernica)', 5, 9, 12),
  ('반딧불이아이비', 'Hedera helix Firefly', 5, 9, 12),
  ('골든잉곳아이비', 'Hedera helix Golden Ingot', 5, 9, 12),
  ('달마시안 아이비', 'Hedera helix Dalmatian', 5, 9, 12),
  ('윌리 아이비', 'Hedera helix Willy', 5, 9, 12),
  ('잉글리시 아이비', 'Hedera helix', 5, 9, 12),
  ('폴리셔스', 'Ming Aralia (Polyscias)', 7, 12, 18),
  -- 호야
  ('호야 카르노사', 'Hoya carnosa', 10, 18, 24),
  ('호야 콤팩타', 'Hoya compacta', 10, 18, 24),
  ('호야 케리', 'Sweetheart Hoya (Hoya kerrii)', 12, 21, 24),
  ('호야 라쿠노사', 'Hoya lacunosa', 9, 16, 24),
  ('호야 빌로바타', 'Hoya bilobata', 9, 16, 24),
  ('호야 크라시페티올라타', 'Hoya crassipetiolata', 10, 18, 24),
  ('호야 로툰디플로라', 'Hoya rotundiflora', 9, 16, 24),
  ('호야 크로니아나', 'Hoya krohniana', 9, 16, 24),
  ('호야 크로니아나 슈퍼에스키모', 'Hoya krohniana Super Eskimo', 9, 16, 24),
  ('호야 휴스켈리아나', 'Hoya heuschkeliana', 9, 16, 24),
  ('호야 휴스켈리아나 바리에가타', 'Hoya heuschkeliana Variegata', 9, 16, 24),
  ('호야 윌버그레이브', 'Hoya Wilbur Graves', 10, 18, 24),
  ('호야 마틸데', 'Hoya Mathilde', 10, 18, 24),
  ('호야 리네아리스', 'Hoya linearis', 8, 14, 24),
  ('호야 오보바타', 'Hoya obovata', 12, 21, 24),
  ('호야 푸베라', 'Hoya pubera', 9, 16, 24),
  ('호야 벨라', 'Hoya bella', 9, 16, 24),
  ('호야 레츠사', 'Hoya retusa', 8, 14, 24),
  ('호야 시기라리스', 'Hoya sigillatis', 10, 18, 24),
  ('호야 폴리네우라', 'Hoya polyneura', 9, 16, 24),
  -- 페페로미아·필레아·소형 관엽
  ('페페로미아 옵투시폴리아', 'Baby Rubber Plant (Peperomia obtusifolia)', 9, 16, 12),
  ('수박 페페로미아', 'Watermelon Peperomia (Peperomia argyreia)', 8, 14, 12),
  ('페페로미아 안굴라타', 'Peperomia angulata', 8, 14, 12),
  ('페페로미아 카페라타', 'Peperomia caperata', 8, 14, 12),
  ('페페로미아 호프', 'Peperomia Hope', 9, 16, 12),
  ('페페로미아 프로스트', 'Peperomia Frost', 8, 14, 12),
  ('필레아 페페로미오이데스', 'Chinese Money Plant (Pilea peperomioides)', 8, 14, 12),
  ('필레아 글라우카', 'Pilea glauca', 6, 11, 12),
  ('필레아 카디에레이', 'Aluminum Plant (Pilea cadierei)', 6, 11, 12),
  ('베고니아 마쿨라타', 'Polka Dot Begonia (Begonia maculata)', 6, 11, 12),
  ('베고니아 렉스', 'Rex Begonia', 5, 10, 12),
  ('베고니아 마소니아나', 'Iron Cross Begonia (Begonia masoniana)', 5, 10, 12),
  ('피토니아', 'Nerve Plant (Fittonia)', 3, 6, 12),
  ('트라데스칸티아 제브리나', 'Wandering Dude (Tradescantia zebrina)', 5, 9, 12),
  ('트리안', 'Muehlenbeckia complexa', 4, 8, 12),
  ('뮬렌베키아', 'Wire Vine (Muehlenbeckia)', 4, 8, 12),
  ('크로톤', 'Croton (Codiaeum variegatum)', 6, 11, 12),
  ('아펠란드라', 'Zebra Plant (Aphelandra squarrosa)', 5, 9, 12),
  ('브레이니아 니보사', 'Snowbush (Breynia nivosa)', 5, 9, 12),
  ('마오리 소포라', 'Prostrate Kowhai (Sophora prostrata)', 5, 9, 12),
  ('아프리칸 바이올렛', 'African Violet (Saintpaulia)', 6, 10, 12),
  ('셀라기넬라', 'Selaginella', 3, 6, 12),
  -- 행잉·공중식물
  ('틸란드시아', 'Air Plant (Tillandsia)', 7, 10, NULL),
  ('틸란드시아 이오난사', 'Tillandsia ionantha', 7, 10, NULL),
  ('틸란드시아 세로그라피카', 'Tillandsia xerographica', 10, 14, NULL),
  ('수염 틸란드시아', 'Spanish Moss (Tillandsia usneoides)', 5, 8, NULL),
  ('립살리스 카스타', 'Mistletoe Cactus (Rhipsalis cassutha)', 9, 16, 18),
  ('립살리스 파라독사', 'Chain Cactus (Rhipsalis paradoxa)', 9, 16, 18),
  ('디시디아', 'Dischidia', 9, 16, 18),
  ('디시디아 넘물라리아', 'String of Nickels (Dischidia nummularia)', 9, 16, 18),
  ('러브체인', 'String of Hearts (Ceropegia woodii)', 10, 18, 18),
  ('녹영', 'String of Pearls (Senecio rowleyanus)', 12, 21, 18),
  -- 고사리류
  ('보스턴고사리', 'Boston Fern (Nephrolepis exaltata)', 3, 6, 12),
  ('아디안텀', 'Maidenhair Fern (Adiantum)', 3, 5, 12),
  ('박쥐란', 'Staghorn Fern (Platycerium)', 6, 10, 18),
  ('블루스타펀', 'Blue Star Fern (Phlebodium aureum)', 4, 8, 12),
  ('아비스', 'Bird''s Nest Fern (Asplenium nidus)', 4, 8, 12),
  ('넉줄고사리', 'Rabbit''s Foot Fern (Davallia)', 4, 8, 12),
  ('프테리스', 'Brake Fern (Pteris)', 3, 6, 12),
  -- 허브·꽃·나무
  ('로즈마리', 'Rosemary', 3, 7, 12),
  ('라벤더', 'Lavender', 4, 8, 12),
  ('바질', 'Basil', 2, 5, 6),
  ('애플민트', 'Apple Mint', 2, 5, 6),
  ('페퍼민트', 'Peppermint', 2, 5, 6),
  ('스피아민트', 'Spearmint', 2, 5, 6),
  ('레몬밤', 'Lemon Balm', 3, 6, 6),
  ('세이지', 'Sage', 4, 8, 12),
  ('오레가노', 'Oregano', 4, 8, 12),
  ('장미허브', 'Vicks Plant (Plectranthus tomentosa)', 4, 8, 12),
  ('타임', 'Thyme', 4, 8, 12),
  ('유칼립투스 폴리안', 'Eucalyptus polyanthemos', 3, 7, 12),
  ('유칼립투스 구니', 'Eucalyptus gunnii', 3, 7, 12),
  ('율마', 'Goldcrest (Cupressus macrocarpa)', 3, 6, 12),
  ('아라우카리아', 'Norfolk Island Pine (Araucaria)', 6, 11, 18),
  ('재스민', 'Jasmine', 4, 8, 12),
  ('마다가스카르 자스민', 'Madagascar Jasmine (Stephanotis)', 5, 9, 12),
  ('치자나무', 'Gardenia', 4, 8, 12),
  ('아라비카 커피나무', 'Arabica Coffee (Coffea arabica)', 4, 8, 12),
  ('올리브나무', 'Olive Tree (Olea europaea)', 5, 10, 18),
  ('레몬나무', 'Lemon Tree', 5, 10, 18),
  ('무화과나무', 'Fig Tree (Ficus carica)', 4, 9, 18),
  ('석류나무', 'Pomegranate', 5, 10, 18),
  ('블루베리', 'Blueberry', 3, 7, 12),
  ('금목서', 'Fragrant Olive (Osmanthus fragrans)', 5, 10, 18),
  ('동백나무', 'Camellia', 5, 9, 18),
  ('남천', 'Heavenly Bamboo (Nandina domestica)', 5, 10, 18),
  ('황칠나무', 'Dendropanax morbiferus', 6, 11, 18),
  ('크루시아', 'Autograph Tree (Clusia rosea)', 8, 14, 18),
  ('수국', 'Hydrangea', 3, 7, 12),
  ('제라늄', 'Geranium (Pelargonium)', 5, 10, 12),
  ('구문초', 'Rose Geranium (Pelargonium graveolens)', 4, 8, 12),
  ('시클라멘', 'Cyclamen', 4, 7, 12),
  ('포인세티아', 'Poinsettia', 5, 9, 12),
  ('꽃기린', 'Crown of Thorns (Euphorbia milii)', 10, 18, 24),
  ('호접란', 'Moth Orchid (Phalaenopsis)', 10, 14, 24),
  ('만천홍', 'Phalaenopsis Mancheonhong', 10, 14, 24),
  ('덴드로비움', 'Dendrobium', 8, 14, 24),
  ('풍란', 'Wind Orchid (Neofinetia falcata)', 7, 12, 24),
  -- 다육·선인장·괴근
  ('선인장', 'Cactus', 14, 35, 24),
  ('금호선인장', 'Golden Barrel Cactus (Echinocactus grusonii)', 15, 40, 24),
  ('백도선', 'Bunny Ears Cactus (Opuntia microdasys)', 14, 35, 24),
  ('귀면각', 'Fairy Castle Cactus (Cereus)', 14, 35, 24),
  ('용신목', 'Blue Myrtle Cactus (Myrtillocactus)', 14, 35, 24),
  ('게발선인장', 'Christmas Cactus (Schlumbergera)', 10, 18, 24),
  ('에케베리아', 'Echeveria', 14, 30, 24),
  ('하월시아', 'Haworthia', 14, 28, 24),
  ('십이지권', 'Zebra Haworthia (Haworthiopsis fasciata)', 14, 28, 24),
  ('염좌', 'Jade Plant (Crassula ovata)', 14, 28, 24),
  ('흑법사', 'Aeonium Zwartkop', 12, 25, 24),
  ('을녀심', 'Sedum pachyphyllum', 12, 25, 24),
  ('벽어연', 'Corpuscularia lehmannii', 14, 28, 24),
  ('리톱스', 'Living Stones (Lithops)', 20, 60, 24),
  ('세덤', 'Sedum', 12, 25, 24),
  ('알로에 베라', 'Aloe vera', 14, 30, 24),
  ('칼랑코에', 'Kalanchoe', 10, 18, 24),
  ('당나귀꼬리', 'Burro''s Tail (Sedum morganianum)', 12, 25, 24),
  ('아가베', 'Agave', 15, 35, 24),
  ('유포르비아 트리고나', 'African Milk Tree (Euphorbia trigona)', 14, 30, 24),
  ('아데니움 오베숨', 'Desert Rose (Adenium obesum)', 10, 30, 24),
  ('스테파니아 에렉타', 'Stephania erecta', 10, 30, 24),
  ('시조바시스 인트리카타', 'Climbing Onion (Schizobasis intricata)', 12, 30, 24),
  ('파키포디움', 'Pachypodium', 10, 30, 24),
  ('파키라', 'Money Tree (Pachira aquatica)', 8, 14, 18),
  ('스투키', 'Sansevieria Stuckyi', 14, 30, 24)
ON CONFLICT(name) DO UPDATE SET
  name_en           = COALESCE(species.name_en, excluded.name_en),
  water_summer_days = COALESCE(species.water_summer_days, excluded.water_summer_days),
  water_winter_days = COALESCE(species.water_winter_days, excluded.water_winter_days),
  repot_months      = COALESCE(species.repot_months, excluded.repot_months);

